FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src src
COPY data data
COPY params.yaml .

ENV MLFLOW_TRACKING_URI=http://mlflow:5000

CMD ["python", "src/data/train.py"]
